# modules:
#   main:
#     OnBeforeEventAdd:
#      - \app\components\bitrix\events\handlers\BeforeEventAdd
#     OnBeforeEventSend:
#       - \app\components\bitrix\events\handlers\BeforeEventSend
#     OnBeforeUserRegister:
#       - \app\components\bitrix\events\handlers\BeforeUserRegister
#     OnBeforeUserUpdate:
#       - \app\components\bitrix\events\handlers\BeforeUserUpdate
